version: '3'

services:
  backend:
    build: ./server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=db
      - PORT=8000
    networks:
      - backend_network
      - frontend_network
    depends_on:
    - db

  frontend:
    build: 
      context: ./client
    restart: always
    ports:
      - "3000:80"
    networks:
      - frontend_network
    depends_on:
      - backend

  db:
    image: mongo
    restart: always
    networks:
      - backend_network
    volumes:
      - mongo_data_step:/data/db
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example


networks:
  backend_network:
  frontend_network:

volumes:
  mongo_data_step:
